import axios from 'axios';
import { Student } from '../interfaces/student';

// apiClient is an axios instance pre-configured with the base URL for the Go backend API.
const apiClient = axios.create({
    baseURL: 'http://localhost:8080', // Base URL for the Go backend API
    headers: {
        'Content-Type': 'application/json',
    },
});

// Fetches all students from the backend.
export const getStudents = async (): Promise<Student[]> => {
    const { data } = await apiClient.get<Student[]>('/students');
    return data;
};

// Fetches a single student by their ID from the backend.
export const getStudentById = async (id: number): Promise<Student> => {
    const { data } = await apiClient.get<Student>(`/students/${id}`);
    return data;
};

// Sends a request to create a new student to the backend.
// studentData should exclude the 'id' field, as it will be generated by the backend.
export const createStudent = async (studentData: Omit<Student, 'id'>): Promise<Student> => {
    const { data } = await apiClient.post<Student>('/students', studentData);
    return data;
};

// Updates an existing student by their ID.
export const updateStudent = async (id: number, studentData: Omit<Student, 'id'>): Promise<Student> => {
    const { data } = await apiClient.put<Student>(`/students/${id}`, studentData);
    return data;
};

// You can add more API functions here for policies, eligibility checks, etc.
// For example:
// interface EligibilityRequest {
//   studentId: number;
//   companyId: string;
// }
// interface EligibilityResult { // Define this based on your Go model
//   studentId: number;
//   companyId: string;
//   isEligible: boolean;
//   reasons: string[];
//   policySpecifics?: string;
// }
// export const checkEligibility = async (payload: EligibilityRequest): Promise<EligibilityResult> => {
//   const response = await apiClient.post<EligibilityResult>('/eligibility/check', payload);
//   return response.data;
// };